---
# Data Science and Artificial Intelliegence Practicum
## 2.2-modul. Data Analysis: Pandas
---

## 2.2.5 - Arithmetics, Sorting, Ranking

In [1]:
import pandas as pd
import numpy as np

#### Arithmetic operators

- `add`, `radd` - Addition (+)
- `sub`, `rsub` - Subtraction (-)
- `mul`, `rmul` - Multiplication (*)
- `div`, `rdiv` - Floating division (/)
- `floordiv`, `rfloordiv` - Integer division (//)
- `mod` - Modulo (%)
- `pow`, `rpow` - Exponential power (\*\*)

All support to substitute a `fill_value` for missing data in one of the inputs.

### arithmetics with `Series`

In [2]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

If one object does not have an existing index in the other, the result will be `NaN`.

In [5]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

### arithmetics with `DataFrame`

In [6]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'), index=['Olma','Anor','Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('abc'), index=['Olma','Anor','Qovun','Anjir'])

In [7]:
df1

        b    c    d
Olma  0.0  1.0  2.0
Anor  3.0  4.0  5.0
Uzum  6.0  7.0  8.0

In [8]:
df2

         a     b     c
Olma   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Qovun  6.0   7.0   8.0
Anjir  9.0  10.0  11.0

In [9]:
df1 + df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

#### `DataFrame.add`
Get Addition of dataframe and other, element-wise (binary operator add).

In [10]:
df1.add(df2)

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

##### `fill_value` : *float or None, default None*
Fill existing missing (NaN) values, and any new element needed for successful DataFrame alignment, with this value before computation. If data in both corresponding DataFrame locations is missing the result will be missing.

In [11]:
df1.add(df2, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

#### `DataFrame.sub`
Get Subtraction of dataframe and other, element-wise (binary operator sub).

In [12]:
df1.sub(2)  # subtract 2 from each df element

        b    c    d
Olma -2.0 -1.0  0.0
Anor  1.0  2.0  3.0
Uzum  4.0  5.0  6.0

In [13]:
df2.sub(df1)  # subtract df1 from df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  1.0  1.0 NaN
Olma  NaN  1.0  1.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

#### `DataFrame.rsub`
Get Subtraction of dataframe and other, element-wise (binary operator rsub).

In [14]:
df1.rsub(df2, fill_value=0) # subtract df1 from df2

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

### Arithmetics with `DataFrame` and `Series`

In [15]:
df = pd.DataFrame(np.arange(1,13.).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a   1.0   2.0    3.0    4.0
b   5.0   6.0    7.0    8.0
c   9.0  10.0   11.0   12.0

#### add `Series` to `DataFrame` by columns

In [16]:
obj = pd.Series([4, 3, 2, 1], index=df.columns)
obj

Olma     4
Anor     3
Qovun    2
Anjir    1
dtype: int64

In [17]:
df + obj

   Olma  Anor  Qovun  Anjir
a   5.0   5.0    5.0    5.0
b   9.0   9.0    9.0    9.0
c  13.0  13.0   13.0   13.0

#### add `Series` to `DataFrame` by rows

In [18]:
obj0 = pd.Series([4, 6, 8], index=df.index)
obj0

a    4
b    6
c    8
dtype: int64

In [21]:
df.add(obj0, axis='rows')

   Olma  Anor  Qovun  Anjir
a   5.0   6.0    7.0    8.0
b  11.0  12.0   13.0   14.0
c  17.0  18.0   19.0   20.0

In [22]:
df.add(obj0)  # default axis='columns'

   Anjir  Anor  Olma  Qovun   a   b   c
a    NaN   NaN   NaN    NaN NaN NaN NaN
b    NaN   NaN   NaN    NaN NaN NaN NaN
c    NaN   NaN   NaN    NaN NaN NaN NaN

In [23]:
df - obj['Olma']

   Olma  Anor  Qovun  Anjir
a  -3.0  -2.0   -1.0    0.0
b   1.0   2.0    3.0    4.0
c   5.0   6.0    7.0    8.0

In [24]:
df.sub(obj['Anor'])

   Olma  Anor  Qovun  Anjir
a  -2.0  -1.0    0.0    1.0
b   2.0   3.0    4.0    5.0
c   6.0   7.0    8.0    9.0

### applying function to `DataFrmae`

In [31]:
df = pd.DataFrame(np.random.randn(3,4),
                  index=list('abc'),
                  columns=['Olma','Anor','Qovun','Anjir']
                  )
df

       Olma      Anor     Qovun     Anjir
a  2.104853 -1.915365  0.783849 -0.627147
b  1.345325 -0.722568  0.768590 -0.508942
c -1.015794  0.170490 -0.024809 -1.087766

#### apply function to each element in `df`

In [32]:
np.abs(df)

       Olma      Anor     Qovun     Anjir
a  2.104853  1.915365  0.783849  0.627147
b  1.345325  0.722568  0.768590  0.508942
c  1.015794  0.170490  0.024809  1.087766

In [33]:
np.round(df)

   Olma  Anor  Qovun  Anjir
a   2.0  -2.0    1.0   -1.0
b   1.0  -1.0    1.0   -1.0
c  -1.0   0.0   -0.0   -1.0

#### by `DataFrame` methods

In [35]:
df.mean()

Olma     0.811461
Anor    -0.822481
Qovun    0.509210
Anjir   -0.741285
dtype: float64

In [36]:
df.abs()

       Olma      Anor     Qovun     Anjir
a  2.104853  1.915365  0.783849  0.627147
b  1.345325  0.722568  0.768590  0.508942
c  1.015794  0.170490  0.024809  1.087766

#### `apply` - apply a function along an axis of the DataFrame

In [39]:
df.apply(np.mean)
df.applymap()

Olma     0.811461
Anor    -0.822481
Qovun    0.509210
Anjir   -0.741285
dtype: float64

In [46]:
df.apply(np.sum, axis='columns')

a    0.346189
b    0.882405
c   -1.957879
dtype: float64

In [48]:
# subtract min element from max
func = lambda x: x.max() - x.min()

In [60]:
df.apply(func, axis='rows')

Olma     3.120646
Anor     2.085855
Qovun    0.808658
Anjir    0.578823
dtype: float64

In [61]:
def foo(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [64]:
df.apply(foo)

         Olma      Anor     Qovun     Anjir
min -1.015794 -1.915365 -0.024809 -1.087766
max  2.104853  0.170490  0.783849 -0.508942

#### `applymap` - apply a function to a Dataframe elementwise

In [66]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [67]:
df.applymap(lambda x: x**2)

   Olma  Anor  Qovun  Anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144

### Sorting

In [68]:
obj = pd.Series([7, 1, 4, 9], index=['d', 'a', 'b', 'c'])
obj

d    7
a    1
b    4
c    9
dtype: int64

#### `Series.sort_index`

In [69]:
# sort Series by index labels
obj.sort_index()

a    1
b    4
c    9
d    7
dtype: int64

#### `Series.sort_values`

In [70]:
# sort by the values
obj.sort_values()

a    1
b    4
d    7
c    9
dtype: int64

#### `DataFrame.sort_index`

In [71]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)
df.head()

   price      brand    model  ...       state country      condition
0   6300     toyota  cruiser  ...  new jersey     usa   10 days left
1   2899       ford       se  ...   tennessee     usa    6 days left
2   5350      dodge      mpv  ...     georgia     usa    2 days left
3  25000       ford     door  ...    virginia     usa  22 hours left
4  27700  chevrolet     1500  ...     florida     usa  22 hours left

[5 rows x 12 columns]

In [72]:
df.sort_index()

      price      brand    model  ...       state country      condition
0      6300     toyota  cruiser  ...  new jersey     usa   10 days left
1      2899       ford       se  ...   tennessee     usa    6 days left
2      5350      dodge      mpv  ...     georgia     usa    2 days left
3     25000       ford     door  ...    virginia     usa  22 hours left
4     27700  chevrolet     1500  ...     florida     usa  22 hours left
...     ...        ...      ...  ...         ...     ...            ...
2494   7800     nissan    versa  ...  california     usa    1 days left
2495   9200     nissan    versa  ...     florida     usa  21 hours left
2496   9200     nissan    versa  ...     florida     usa  21 hours left
2497   9200     nissan    versa  ...     florida     usa    2 days left
2498   9200     nissan    versa  ...     florida     usa  21 hours left

[2499 rows x 12 columns]

In [73]:
df.sort_index(axis=1)  # sort by column names

          brand   color  ...                  vin  year
0        toyota   black  ...    jtezu11f88k007763  2008
1          ford  silver  ...    2fmdk3gc4bbb02217  2011
2         dodge  silver  ...    3c4pdcgg5jt346413  2018
3          ford    blue  ...    1ftfw1et4efc23745  2014
4     chevrolet     red  ...    3gcpcrec2jg473991  2018
...         ...     ...  ...                  ...   ...
2494     nissan     red  ...    3n1cn7ap9kl880319  2019
2495     nissan  silver  ...    3n1cn7ap5jl884088  2018
2496     nissan  silver  ...    3n1cn7ap9jl884191  2018
2497     nissan   black  ...    3n1cn7ap3jl883263  2018
2498     nissan  silver  ...    3n1cn7ap4jl884311  2018

[2499 rows x 12 columns]

In [76]:
df.sort_index(ascending=False)  # reverse order

      price      brand    model  ...       state country      condition
2498   9200     nissan    versa  ...     florida     usa  21 hours left
2497   9200     nissan    versa  ...     florida     usa    2 days left
2496   9200     nissan    versa  ...     florida     usa  21 hours left
2495   9200     nissan    versa  ...     florida     usa  21 hours left
2494   7800     nissan    versa  ...  california     usa    1 days left
...     ...        ...      ...  ...         ...     ...            ...
4     27700  chevrolet     1500  ...     florida     usa  22 hours left
3     25000       ford     door  ...    virginia     usa  22 hours left
2      5350      dodge      mpv  ...     georgia     usa    2 days left
1      2899       ford       se  ...   tennessee     usa    6 days left
0      6300     toyota  cruiser  ...  new jersey     usa   10 days left

[2499 rows x 12 columns]

#### `DataFrame.sort_values`

In [79]:
df.sort_values(by='price', ascending=False)

      price          brand       model  ...      state country      condition
502   84900  mercedes-benz    sl-class  ...    florida     usa    2 days left
1340  74000           ford         drw  ...   illinois     usa    2 days left
1336  70000           ford         drw  ...   illinois     usa    2 days left
277   67000          dodge  challenger  ...       ohio     usa  21 hours left
1215  65500           ford         srw  ...    indiana     usa  21 hours left
...     ...            ...         ...  ...        ...     ...            ...
141       0          dodge         van  ...       utah     usa    2 days left
391       0       cadillac       coupe  ...   virginia     usa    9 days left
285       0           ford        door  ...   oklahoma     usa  17 hours left
290       0          mazda        door  ...    indiana     usa  16 hours left
354       0           ford      pickup  ...  tennessee     usa    2 days left

[2499 rows x 12 columns]

### Ranking
`DataFrame.rank` - compute numerical data ranks (1 through n) along axis

In [87]:
# rank by year
df['rating'] = df['year'].rank()
df

      price      brand    model  ...  country      condition  rating
0      6300     toyota  cruiser  ...      usa   10 days left    70.5
1      2899       ford       se  ...      usa    6 days left   115.0
2      5350      dodge      mpv  ...      usa    2 days left  1362.0
3     25000       ford     door  ...      usa  22 hours left   336.5
4     27700  chevrolet     1500  ...      usa  22 hours left  1362.0
...     ...        ...      ...  ...      ...            ...     ...
2494   7800     nissan    versa  ...      usa    1 days left  2005.5
2495   9200     nissan    versa  ...      usa  21 hours left  1362.0
2496   9200     nissan    versa  ...      usa  21 hours left  1362.0
2497   9200     nissan    versa  ...      usa    2 days left  1362.0
2498   9200     nissan    versa  ...      usa  21 hours left  1362.0

[2499 rows x 13 columns]

In [89]:
df.sort_values("year")

      price      brand     model  ...  country      condition  rating
32    29800  chevrolet    camaro  ...      usa  22 hours left     1.0
405      25       ford      door  ...      usa  17 hours left     2.0
545       0        gmc      door  ...      usa  18 hours left     3.0
362      25       ford    pickup  ...      usa    2 days left     4.5
322       0       ford   chassis  ...      usa  19 hours left     4.5
...     ...        ...       ...  ...      ...            ...     ...
426   55600      lexus        gx  ...      usa    2 days left  2475.5
806   28300  chevrolet  colorado  ...      usa    2 days left  2475.5
2322  15000     nissan    altima  ...      usa    2 days left  2475.5
2344  20100     nissan     rogue  ...      usa  14 hours left  2475.5
1388  17000       ford    fusion  ...      usa    2 days left  2475.5

[2499 rows x 13 columns]

In [91]:
# rank by mileage
df['rating'] = df['mileage'].rank()
df.sort_values('mileage')

      price      brand   model  ...  country      condition  rating
545       0        gmc    door  ...      usa  18 hours left     3.5
504     100  peterbilt   truck  ...      usa  17 hours left     3.5
1619    650       ford    door  ...      usa    2 days left     3.5
309       0  chevrolet    door  ...      usa  18 hours left     3.5
1236   4200       ford    door  ...      usa    2 days left     3.5
...     ...        ...     ...  ...      ...            ...     ...
531    2000  chevrolet  pickup  ...      usa  21 hours left  2495.0
490     475  peterbilt   truck  ...      usa  17 hours left  2496.0
516       0  peterbilt   truck  ...      usa  17 hours left  2497.0
1827   3200       ford    door  ...      usa  21 hours left  2498.0
528    1025  peterbilt   truck  ...      usa  17 hours left  2499.0

[2499 rows x 13 columns]

In [94]:
# rank by price
df['rating'] = df['price'].rank(method='min')
df.sort_values('price')

      price          brand       model  ...  country      condition  rating
410       0      chevrolet        door  ...      usa    2 days left     1.0
330       0           ford        door  ...      usa  19 hours left     1.0
331       0           ford        door  ...      usa  17 hours left     1.0
339       0           ford        door  ...      usa    2 days left     1.0
496       0           ford      pickup  ...      usa  17 hours left     1.0
...     ...            ...         ...  ...      ...            ...     ...
1215  65500           ford         srw  ...      usa  21 hours left  2495.0
277   67000          dodge  challenger  ...      usa  21 hours left  2496.0
1336  70000           ford         drw  ...      usa    2 days left  2497.0
1340  74000           ford         drw  ...      usa    2 days left  2498.0
502   84900  mercedes-benz    sl-class  ...      usa    2 days left  2499.0

[2499 rows x 13 columns]