---
# Data Science and Artificial Intelliegence Practicum
## 2.2-modul. Data Analysis: Pandas
---

## 2.2.2 - DataFrame

In [1]:
import pandas as pd

#### creating DataFrame from a dictionary

In [2]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
        'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
        'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
        }

In [3]:
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [6]:
# return the first n rows. n:int, default 5
df.head()

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [7]:
df.head(3)

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56

In [10]:
# assigning order of columns
df = pd.DataFrame(data, columns=['Yil','Temp','Aholi soni'])
df.head()

    Yil  Temp  Aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.5
2  2019  1.56        32.9
3  2018  1.62        32.5
4  2017  1.65        31.9

In [12]:
df = pd.DataFrame(data, columns=['Yil', 'Temp', 'Aholi soni', 'YaIM'])
df.head()

    Yil  Temp  Aholi soni YaIM
0  2021  1.54        33.9  NaN
1  2020  1.48        33.5  NaN
2  2019  1.56        32.9  NaN
3  2018  1.62        32.5  NaN
4  2017  1.65        31.9  NaN

#### like `Series` we can give our own values to indexes in `DataFrame` with **`index`** parameter

In [27]:
df = pd.DataFrame(data, columns=['Yil','Temp','Aholi soni','YaIM'], index=[21, 20, 19, 18, 17, 16, 15, 10])
df

     Yil  Temp  Aholi soni YaIM
21  2021  1.54        33.9  NaN
20  2020  1.48        33.5  NaN
19  2019  1.56        32.9  NaN
18  2018  1.62        32.5  NaN
17  2017  1.65        31.9  NaN
16  2016  1.66        31.4  NaN
15  2015  1.64        30.9  NaN
10  2010  1.53        28.5  NaN

#### we can extract any column of `DataFrame` as `Series` object

##### as a attribute

In [28]:
obj = df.Yil
obj

21    2021
20    2020
19    2019
18    2018
17    2017
16    2016
15    2015
10    2010
Name: Yil, dtype: int64

In [29]:
type(obj)

pandas.core.series.Series

##### as a dictionary key

In [30]:
obj2 = df['Aholi soni']
obj2

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [31]:
type(obj2)

pandas.core.series.Series

In [36]:
# giving values to any column
df.YaIM = 1600
df

     Yil  Temp  Aholi soni  YaIM
21  2021  1.54        33.9  1600
20  2020  1.48        33.5  1600
19  2019  1.56        32.9  1600
18  2018  1.62        32.5  1600
17  2017  1.65        31.9  1600
16  2016  1.66        31.4  1600
15  2015  1.64        30.9  1600
10  2010  1.53        28.5  1600

#### with `Series` we can change any values in columns, in this case we have to define index of each row

In [38]:
val = pd.Series([1750, 1560, 1270], index=[21, 18, 10])

In [41]:
df.YaIM = val
df

     Yil  Temp  Aholi soni    YaIM
21  2021  1.54        33.9  1750.0
20  2020  1.48        33.5     NaN
19  2019  1.56        32.9     NaN
18  2018  1.62        32.5  1560.0
17  2017  1.65        31.9     NaN
16  2016  1.66        31.4     NaN
15  2015  1.64        30.9     NaN
10  2010  1.53        28.5  1270.0

#### in order to change values in columns we can define list which has equal length to rows of the column

In [48]:
YAIM = [1700, 1670, 1600, 1590, 1400, 1300, 1350, 1360]

In [49]:
df.YaIM = YAIM
df

     Yil  Temp  Aholi soni  YaIM
21  2021  1.54        33.9  1700
20  2020  1.48        33.5  1670
19  2019  1.56        32.9  1600
18  2018  1.62        32.5  1590
17  2017  1.65        31.9  1400
16  2016  1.66        31.4  1300
15  2015  1.64        30.9  1350
10  2010  1.53        28.5  1360

#### in this example, we are creating a new column called "1500+", then values of this column will be True if values of "YaIM" column is greater than 1500 and vice versa

In [51]:
df["1500+"] = df.YaIM > 1500
df

     Yil  Temp  Aholi soni  YaIM  1500+
21  2021  1.54        33.9  1700   True
20  2020  1.48        33.5  1670   True
19  2019  1.56        32.9  1600   True
18  2018  1.62        32.5  1590   True
17  2017  1.65        31.9  1400  False
16  2016  1.66        31.4  1300  False
15  2015  1.64        30.9  1350  False
10  2010  1.53        28.5  1360  False

#### like a `dictionary` we can remove columns from `DataFrame` with **`del`** operator

In [52]:
del df["1500+"]
df

     Yil  Temp  Aholi soni  YaIM
21  2021  1.54        33.9  1700
20  2020  1.48        33.5  1670
19  2019  1.56        32.9  1600
18  2018  1.62        32.5  1590
17  2017  1.65        31.9  1400
16  2016  1.66        31.4  1300
15  2015  1.64        30.9  1350
10  2010  1.53        28.5  1360

#### creating `DataFrame` with nested dictionaries

In [59]:
data2 = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}

In [62]:
df2 = pd.DataFrame(data2)
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

#### we can give a name to `DateFrame` index

In [64]:
df2.index.name = "Yil"
df2

      Uzbekistan  Kazakhstan
Yil
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

lug'atdan faqagina ma'lum bir qiymatlarni ajratib olishni istasak index ni o'zimiz ko'rsatishimiz mumkin.
#### if we want to extract only some values from a dictionary, we can use index for each row

In [67]:
df2 = pd.DataFrame(data2, index=[2021, 2019, 2017])
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [70]:
# return a NumPy representation of the DataFrame
df2.values

array([[33.9, 18.9],
       [32.9, 18.5],
       [31.9, 18.1]])

#### we can use *`T`* (transpose) attribute in order to change the positions of columns and rows

In [68]:
df2.T

            2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1