---
# Data Science and Artificial Intelliegence Practicum
## 3.1-modul. Data Wrangling
---

## 3.1.3 - SQLite 1 - Read from SQL

MAʼLUMOTLAR BAZASINI LOYIHALASH. 1-QISM -> https://mohirdev.uz/ma%ca%bclumotlar-bazasini-loyihalash-1-qism/

### **SQL** - *Structured Query Language*

**Some of The Most Important SQL Commands**

- `SELECT` - extracts data from a database
- `UPDATE` - updates data in a database
- `DELETE` - deletes data from a database
- `INSERT INTO` - inserts new data into a database
- `CREATE DATABASE` - creates a new database
- `ALTER DATABASE` - modifies a database
- `CREATE TABLE` - creates a new table
- `ALTER TABLE` - modifies a table
- `DROP TABLE` - deletes a table
- `CREATE INDEX` - creates an index (search key)
- `DROP INDEX` - deletes an index

### PostgreSQL

1. Set up a `psycopg2` library to work with PostgreSQL

In [ ]:
# !pip install psycopg2-binary
# import psycopg2 as psql

2. Connect to PostgreSQL

**`psycopg2.connect`**

The basic connection parameters are:

- **`dbname`** – the database name (database is a deprecated alias)
- **`user`** – user name used to authenticate
- **`password`** – password used to authenticate
- **`host`** – database host address (defaults to UNIX socket if not provided)
- **`port`** – connection port number (defaults to 5432 if not provided)

In [ ]:
# pdb = psql.connect(
#     host = "localhost",
#     database = "example_db",
#     user = "postgres",
#     password = "myDBPass001",
# )

# cursor = pdb.cursor()
# cursor.execute("SELECT version();")
# print(cursor.fetchone())

### SQLite

importing modules

In [ ]:
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

downloading data

In [ ]:
url = "https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip"

!wget $url
!unzip "chinook.zip"

--2022-03-21 06:40:45--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 151.139.128.11
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|151.139.128.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.02s

2022-03-21 06:40:45 (12.8 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [ ]:
db = sql.connect("chinook.db")
cursor = db.cursor()

#### tables in the *chinook* database

In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

#### the number of rows in the table

In [ ]:
cursor.execute("SELECT COUNT (*) FROM customers")
cursor.fetchone()

(59,)

#### columns in the table
`PRAGMA` - used to query information about a specific table

In [ ]:
# PRAGMA command is specific to SQLite
cursor.execute("PRAGMA table_info(customers);")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

#### Read a SQL table into a DataFrame
read only limited rows

In [ ]:
query = "SELECT * FROM customers LIMIT 5"
df = pd.read_sql(query, db, index_col="CustomerId")
df

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

read entire table

In [ ]:
query = "SELECT * FROM customers"
df = pd.read_sql(query, db, index_col="CustomerId")
df.sample(5)

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4

selecting specific columns from table

In [ ]:
query = "SELECT FirstName, LastName, City, State, Phone, Email FROM customers"
pd.read_sql(query, db).head(10)

,FirstName,LastName,City,State,Phone,Email
0,Luís,Gonçalves,São José dos Campos,SP,+55 (12) 3923-5555,luisg@embraer.com.br
1,Leonie,Köhler,Stuttgart,None,+49 0711 2842222,leonekohler@surfeu.de
2,François,Tremblay,Montréal,QC,+1 (514) 721-4711,ftremblay@gmail.com
3,Bjørn,Hansen,Oslo,None,+47 22 44 22 22,bjorn.hansen@yahoo.no
4,František,Wichterlová,Prague,None,+420 2 4172 5555,frantisekw@jetbrains.com
5,Helena,Holý,Prague,None,+420 2 4177 0449,hholy@gmail.com
6,Astrid,Gruber,Vienne,None,+43 01 5134505,astrid.gruber@apple.at
7,Daan,Peeters,Brussels,None,+32 02 219 03 03,daan_peeters@apple.be
8,Kara,Nielsen,Copenhagen,None,+453 3331 9991,kara.nielsen@jubii.dk
9,Eduardo,Martins,São Paulo,SP,+55 (11) 3033-5446,eduardo@woodstock.com.br

In [ ]:
query = "SELECT * FROM customers ORDER BY Country"
pd.read_sql(query, db, index_col="CustomerId").head(10)

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3

In [ ]:
query = "SELECT * FROM customers ORDER BY City DESC"
pd.read_sql(query, db, index_col="CustomerId").head(10)

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3

#### `DISTINCT` clause allows us to remove the duplicate rows in the result set

In [ ]:
cursor.execute("SELECT DISTINCT Country FROM customers")
cursor.fetchall()

[('Brazil',),
 ('Germany',),
 ('Canada',),
 ('Norway',),
 ('Czech Republic',),
 ('Austria',),
 ('Belgium',),
 ('Denmark',),
 ('USA',),
 ('Portugal',),
 ('France',),
 ('Finland',),
 ('Hungary',),
 ('Ireland',),
 ('Italy',),
 ('Netherlands',),
 ('Poland',),
 ('Spain',),
 ('Sweden',),
 ('United Kingdom',),
 ('Australia',),
 ('Argentina',),
 ('Chile',),
 ('India',)]

In [ ]:
# getting result as DF
pd.read_sql("SELECT DISTINCT Country FROM customers", db).head()

          Country
0          Brazil
1         Germany
2          Canada
3          Norway
4  Czech Republic

#### `WHERE` clause is used to filter records.
It is used to extract only those records that fulfill a specified condition.

In [ ]:
# filter by country: Brazil
query = "SELECT * FROM customers WHERE Country='Brazil'"
pd.read_sql(query, db, index_col="CustomerId").head(10)

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4

In [ ]:
# filter by countreis: Brazil and USA

# 1. let's count customers
query = "SELECT COUNT (*) FROM customers WHERE Country IN ('Brazil', 'USA')"
cursor.execute(query)
cursor.fetchone()

(18,)

In [ ]:
# 2. read into DF
query = "SELECT Firstname, LastName, Country, Phone FROM customers WHERE Country IN ('Brazil', 'USA')"
pd.read_sql(query, db)

    FirstName    LastName Country               Phone
0        Luís   Gonçalves  Brazil  +55 (12) 3923-5555
1     Eduardo     Martins  Brazil  +55 (11) 3033-5446
2   Alexandre       Rocha  Brazil  +55 (11) 3055-3278
3     Roberto     Almeida  Brazil  +55 (21) 2271-7000
4    Fernanda       Ramos  Brazil  +55 (61) 3363-5547
5       Frank      Harris     USA   +1 (650) 253-0000
6        Jack       Smith     USA   +1 (425) 882-8080
7    Michelle      Brooks     USA   +1 (212) 221-3546
8         Tim       Goyer     USA   +1 (408) 996-1010
9         Dan      Miller     USA   +1 (650) 644-3358
10      Kathy       Chase     USA   +1 (775) 223-7665
11    Heather     Leacock     USA   +1 (407) 999-7788
12       John      Gordon     USA   +1 (617) 522-1333
13      Frank     Ralston     USA   +1 (312) 332-3232
14     Victor     Stevens     USA   +1 (608) 257-0597
15    Richard  Cunningham     USA   +1 (817) 924-7272
16    Patrick        Gray     USA   +1 (520) 622-4200
17      Julia     Barnett     USA   +1 (801) 531-7272

#### Close the database

In [ ]:
db.close()