---
# Data Science and Artificial Intelliegence Practicum
## 3.2-modul. Data Wrangling
---

## 3.2.5 - Outliers. Random Sample

In [22]:
import pandas as pd
import numpy as np

### Detecting and Handling Outliers

In [23]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/MOCK_USER_DATA.csv",
                 index_col=0)
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [24]:
df.describe()

               age
count   100.000000
mean    145.660000
std     565.631411
min     -85.000000
25%      22.750000
50%      53.500000
75%      84.250000
max    4444.000000

#### working on **age** column

filter data which has age greater than 123

In [25]:
df[df['age'] > 123]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

filter data which has age less than 0

In [26]:
df[df['age'] < 0]

   first_name  last_name                           email       gender  age
id
11     Elijah      Heine                eheinea@imdb.com     Bigender  -85
19      Luisa  Bradborne            lbradbornei@fema.gov       Female  -75
21      Levin     Worner                lwornerk@ihg.com  Genderqueer  -43
33   Ebenezer    Greeves           egreevesw@myspace.com         Male  -26
38       Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer  -42
90  Zachariah      Meins            zmeins2h@weather.com         Male  -69

In [27]:
# combine filters
df[(df['age'] > 123) | (df['age'] < 0)]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
11      Elijah      Heine                eheinea@imdb.com     Bigender   -85
19       Luisa  Bradborne            lbradbornei@fema.gov       Female   -75
21       Levin     Worner                lwornerk@ihg.com  Genderqueer   -43
33    Ebenezer    Greeves           egreevesw@myspace.com         Male   -26
38        Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer   -42
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
90   Zachariah      Meins            zmeins2h@weather.com         Male   -69
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

let's turn negative age values into positive with `numpy.abs`

In [28]:
df['age'] = df['age'].apply(np.abs)
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [29]:
# check if there is no any negative value
df[df['age'] < 0]

Empty DataFrame
Columns: [first_name, last_name, email, gender, age]
Index: []

let's drop age values that are greater than 123

In [30]:
# get index of rows to be droppped
idx = df[df['age'] > 123].index
# drop outliers
df.drop(index=idx, inplace=True)
# describe dataframe
df.describe()

              age
count   93.000000
mean    52.612903
std     29.978265
min      1.000000
25%     29.000000
50%     52.000000
75%     77.000000
max    100.000000

#### working on **gender** column

In [31]:
df['gender'].value_counts()

Male           21
Bigender       12
Genderfluid    11
Female         11
Non-binary     10
Genderqueer    10
Agender         9
Polygender      9
Name: gender, dtype: int64

filtering only **Male**s and **Female**s

In [32]:
df[df['gender'].isin(['Male', 'Female'])]

   first_name     last_name                         email  gender  age
id
2     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
19      Luisa     Bradborne          lbradbornei@fema.gov  Female   75
22        Ray         Padly           rpadlyl@twitpic.com    Male   85
26   Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
29      Biron      Acklands        backlandss@comsenz.com    Male   13
33   Ebenezer       Greeves         egreevesw@myspace.com    Male   26
34     Brooks          Vose             bvosex@amazon.com  Female   34
36        Axe       Arundel           aarundelz@yahoo.com  Female   14
43       Bili     Swetenham        bswetenham16@europa.eu    Male   23
46     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
58     Brynna        Worsom              bworsom1l@wp.com    Male   66
61       Page       Merrell     pmerrell1o@slideshare.net    Male    1
62     Kennan         Visco          kvisco1p@jiathis.com  Female   94
63   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
67     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
70      Ambur        Aickin           aaickin1x@about.com    Male   60
72   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
74      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
76      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
77     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
81       Alex         Darth    adarth28@ezinearticles.com  Female   98
86    Rogerio          Akid           rakid2d@latimes.com  Female    3
87      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
88       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
90  Zachariah         Meins          zmeins2h@weather.com    Male   69
91      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
94     Sheree        Cockin     scockin2l@accuweather.com  Female   94
97     Kattie       Claxson        kclaxson2o@booking.com  Female   18

### Shuffle DataFrame Rows

#### `numpy.random.permuatation`

Randomly permute a sequence, or return a permuted range.

In [33]:
# example
np.random.permutation(20)

array([10,  4, 14,  3, 18, 11,  0,  1, 17, 16,  7, 19,  9,  2, 12, 15, 13,
        6,  5,  8])

#### `DataFrame.take`
Return the elements in the given *positional* indices along an axis.

In [34]:
# example 1
df.take([0,1,2,3,6,10,30,80])

   first_name   last_name                         email       gender  age
id
1     Dorothy     Verryan             dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham  kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon  mhabbershon4@sourceforge.net       Female   48
8         Nye   Anthiftle      nanthiftle7@examiner.com      Agender   99
12  Raffaello   Firminger     rfirmingerb@bloomberg.com       Female   74
32  Mirabelle  Matthewson  mmatthewsonv@list-manage.com      Agender   44
87      Peder      Murrie       pmurrie2e@bloglovin.com         Male   69

In [35]:
# example 2
df.take(np.arange(10))

   first_name   last_name                         email       gender  age
id
1     Dorothy     Verryan             dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham  kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon  mhabbershon4@sourceforge.net       Female   48
6       Glynn      Ebbing        gebbing5@rakuten.co.jp  Genderfluid   77
7       Wendy     Popland              wpopland6@cbc.ca  Genderfluid   67
8         Nye   Anthiftle      nanthiftle7@examiner.com      Agender   99
9         Der      Neames      dneames8@ycombinator.com     Bigender   77
10      David    Meredyth    dmeredyth9@telegraph.co.uk       Female   68
11     Elijah       Heine              eheinea@imdb.com     Bigender   85

we can see rows are ordered by **id** in the dataframe

In [36]:
df.head()

   first_name   last_name                         email       gender  age
id
1     Dorothy     Verryan             dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham  kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon  mhabbershon4@sourceforge.net       Female   48
6       Glynn      Ebbing        gebbing5@rakuten.co.jp  Genderfluid   77

let's shuffle dataframe rows

In [37]:
df.shape

(93, 5)

In [38]:
randlist = np.random.permutation(93)
randlist

array([77, 60, 38, 59, 15, 39, 62, 46, 35, 65, 23, 48, 14, 80, 51, 37, 40,
       88, 17, 81, 57, 11, 84, 31, 44,  9, 21, 26, 28,  2, 32, 53, 24, 64,
       25, 56, 89, 22, 86, 72,  4, 85, 55,  0, 76,  5, 30, 42,  7, 18, 12,
       10, 71, 47, 20, 90, 34, 19, 66, 13, 68, 70, 52, 58, 29, 87, 74, 45,
       73, 78,  3, 67, 33, 49, 69,  8, 16, 36, 63, 82, 50, 27, 92, 54, 79,
       43, 91, 61, 75,  6,  1, 83, 41])

In [39]:
df.take(randlist)

   first_name    last_name                       email       gender  age
id
84      Tildi     Phythien      tphythien2b@ustream.tv  Genderfluid   76
66     Alejoa   Abrahamoff       aabrahamoff1t@com.com   Polygender   28
41   Katheryn     Ashleigh      kashleigh14@devhub.com      Agender   36
64      Carla       Rumney         crumney1r@weibo.com   Polygender   56
17      Byram  Martynikhin   bmartynikhing@jiathis.com         Male   40
..        ...          ...                         ...          ...  ...
82     Wanids     Sifflett      wsifflett29@taobao.com   Polygender   20
8         Nye    Anthiftle    nanthiftle7@examiner.com      Agender   99
2     Pietrek      Scanlin      pscanlin1@yolasite.com         Male   91
90  Zachariah        Meins        zmeins2h@weather.com         Male   69
44     Marice    Champneys  mchampneys17@bigcartel.com     Bigender   49

[93 rows x 5 columns]

### Random Sampling

#### `DataFrame.sample`
Return a random sample of items from an axis of object.

In [40]:
df.sample(3)

   first_name last_name                           email       gender  age
id
31   Barbabas   Ginnety           bginnetyu@oaic.gov.au  Genderqueer   87
98       Clem   Fullerd  cfullerd2p@creativecommons.org     Bigender   55
55      Hiram  Bringloe              hbringloe1i@pen.io   Polygender   50

##### `replace` parameter
**replace :** ***bool, default False*** -> Allow or disallow sampling of the same row more than once.

In [41]:
df.sample(10, replace=True)

   first_name    last_name                           email       gender  age
id
91      Judas       Maffin           jmaffin2i@dropbox.com         Male    3
54    Gregory        Criag         gcriag1h@purevolume.com   Polygender   50
42     Dermot       Dragge          ddragge15@google.co.jp  Genderfluid   37
5    Mohammed   Habbershon    mhabbershon4@sourceforge.net       Female   48
43       Bili    Swetenham          bswetenham16@europa.eu         Male   23
77     Rudolf       Kalewe             rkalewe24@fotki.com         Male   12
13    Kristan      Abriani              kabrianic@phoca.cz   Polygender   29
55      Hiram     Bringloe              hbringloe1i@pen.io   Polygender   50
38       Hana     Langwade  hlangwade11@washingtonpost.com  Genderqueer   42
17      Byram  Martynikhin       bmartynikhing@jiathis.com         Male   40

Note that the `62` index came out twice.